import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "@/components/Providers";
import { TelegramInit } from "@/components/TelegramInit";
import { Header } from "@/components/Header";
import { Toaster } from "sonner";
import Script from "next/script";

// DepartureMono - the pixel-mono face from the hangman/mines apps.
const departureMono = localFont({
  src: "./fonts/DepartureMono-Regular.woff",
  variable: "--font-mono",
  display: "swap",
});

const TITLE = "Confidential Mafia | Inco";
const DESCRIPTION =
  "Social deduction in Telegram with hidden roles and hidden night actions, kept genuinely secret on Inco.";

// og/twitter images are generated by app/opengraph-image.tsx + twitter-image.tsx.
export const metadata: Metadata = {
  metadataBase: new URL("https://confidential-deck.vercel.app"),
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: "website",
    url: "/",
    siteName: "Confidential Deck",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    site: "@inconetwork",
    creator: "@inconetwork",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning lang="en" className="dark">
      <body suppressHydrationWarning className={`min-h-screen font-mono ${departureMono.variable}`}>
        {/* Telegram Mini App SDK -- must load before any code reads window.Telegram.WebApp */}
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
        <Providers>
          <TelegramInit />
          <Header />
          {children}
        </Providers>
        <Toaster
          position="bottom-center"
          toastOptions={{
            style: {
              background: "hsl(var(--card))",
              color: "hsl(var(--foreground))",
              border: "1px solid hsl(var(--border))",
              fontFamily: "var(--font-mono), ui-monospace, monospace",
              fontSize: "13px",
              borderRadius: "0",
            },
          }}
        />
      </body>
    </html>
  );
}
